routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('front.welcome');
});

Route::get('/print', function () {
    return view('print');
});
// Route::get('/login', function() {
//     return view('front.login');
// })->name('login');

Auth::routes();
Route::get('register/{token?}', [App\Http\Controllers\Auth\RegisterController::class, 'view'])->name('reg');
Route::get('register', [App\Http\Controllers\Auth\RegisterController::class, 'view']);

// Route::post('add_akun_transaksi_kantor', 'AkunController@insertTransaksiKantor')->name('add_akun_transaksi_kantor');
Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');
Route::get('/profil_perusahaan', [App\Http\Controllers\DashboardController::class, 'pageProfilPerusahaan'])->name('profil_perusahaan');
Route::get('/data', [App\Http\Controllers\DashboardController::class, 'PageData'])->name('data');
Route::get('/anggaran', [App\Http\Controllers\CatatanController::class, 'pageAnggaran'])->name('anggaran');
Route::get('/neraca/{date_range?}', [App\Http\Controllers\CatatanController::class, 'pageNeraca'])->name('neraca');
Route::get('/transaksi_proyek/{date_range?}', [App\Http\Controllers\CatatanController::class, 'pageTransaksiProyek'])->name('transaksi_proyek');
Route::get('/transaksi_proyek_with_type/{type?}', [App\Http\Controllers\CatatanController::class, 'pageTransaksiProyekWithType'])->name('transaksi_proyek_withfilter');
Route::get('/transaksi_kantor/{date_range?}', [App\Http\Controllers\CatatanController::class, 'pageTransaksiKantor'])->name('transaksi_kantor');
Route::get('/transaksi_kantor_with_type/{type?}', [App\Http\Controllers\CatatanController::class, 'pageTransaksiKantorWithType'])->name('transaksi_kantor_with_type');
Route::get('/hutang_piutang', [App\Http\Controllers\CatatanController::class, 'pageHutangPiutang'])->name('hutang_piutang');
Route::get('/gudang/{date_range?}', [App\Http\Controllers\GudangController::class, 'pageGudang'])->name('gudang');
Route::get('/profile', [App\Http\Controllers\ProfileController::class, 'index'])->name('profile');

Route::get('/manajemen_proyek', [App\Http\Controllers\Proyek\ManajemenProyekController::class, 'index'])->name('manajemen_proyek');
Route::post('/users/update', [App\Http\Controllers\ProfileController::class,'update'])->name('users.update');

Route::get('/laba_rugi/{id_proyek?}/{date_range?}', [App\Http\Controllers\LaporanController::class, 'pageLabaRugi'])->name('laba_rugi');
Route::get('/laba_rugi_proyek/{id_proyek?}/{date_range?}', [App\Http\Controllers\LaporanController::class, 'pageLabaRugiProyek'])->name('laba_rugi_proyek');
Route::get('/laba_rugi_kantor/{date_range?}', [App\Http\Controllers\LaporanController::class, 'pageLabaRugiKantor'])->name('laba_rugi_kantor');

//Route edit perusahaan
Route::prefix('perusahaan')->name('perusahaan.')->group(function () {
    Route::post('/edit', [App\Http\Controllers\DashboardController::class, 'edit'])->name('edit');
    // Route::get('/delete/{id}', [App\Http\Controllers\GudangController::class, 'delete'])->name('delete');
});

// Route perusahaan
Route::post('create_perusahaan', [App\Http\Controllers\dashboard\PerusahaanController::class, 'insert'])->name('create_perusahaan');
Route::post('invite_anggota', [App\Http\Controllers\dashboard\PerusahaanController::class, 'invite'])->name('invite_anggota');
Route::post('acc_invite', [App\Http\Controllers\dashboard\PerusahaanController::class, 'acc_invite'])->name('acc_invite');
Route::post('rej_invite', [App\Http\Controllers\dashboard\PerusahaanController::class, 'rej_invite'])->name('rej_invite');
Route::post('edit_role', [App\Http\Controllers\dashboard\PerusahaanController::class, 'edit_role'])->name('edit_role');
Route::post('delete_member', [App\Http\Controllers\dashboard\PerusahaanController::class, 'delete_member'])->name('delete_member');

//Route Gudang
Route::post('create_gudang', [App\Http\Controllers\GudangController::class, 'create'])->name('create_gudang');
Route::prefix('gudang')->name('gudang.')->group(function () {
    Route::post('/edit', [App\Http\Controllers\GudangController::class, 'edit'])->name('edit');
    Route::get('/delete/{id}', [App\Http\Controllers\GudangController::class, 'delete'])->name('delete');
});
Route::post('form_neraca', [App\Http\Controllers\AkunController::class, 'addAkunNeraca'])->name('form_neraca');
Route::post('form_pemasok', [App\Http\Controllers\AkunController::class, 'addPemasok'])->name('form_pemasok');
Route::post('form_proyek', [App\Http\Controllers\AkunController::class, 'addProyek'])->name('form_proyek');
Route::post('form_transaksi_proyek', [App\Http\Controllers\AkunController::class, 'addAkunTransaksiProyek'])->name('form_transaksi_proyek');
Route::post('form_transaksi_kantor', [App\Http\Controllers\AkunController::class, 'addAkunTransaksiKantor'])->name('form_transaksi_kantor');

Route::get('/delete_neraca/{nama}', [App\Http\Controllers\AkunController::class, 'delAkunNeraca']);
Route::get('/delete_akun_kantor/{nama}', [App\Http\Controllers\AkunController::class, 'delAkunTransaksiKantor']);
Route::get('/delete_akun_proyek/{nama}', [App\Http\Controllers\AkunController::class, 'delAkunTransaksiProyek']);
Route::get('/delete_pemasok/{nama}', [App\Http\Controllers\AkunController::class, 'delPemasok']);
Route::get('/delete_proyek/{nama}', [App\Http\Controllers\AkunController::class, 'delProyek']);

Route::post('edit_neraca', [App\Http\Controllers\AkunController::class, 'editAkunNeraca'])->name('edit_neraca');
Route::post('edit_akun_proyek', [App\Http\Controllers\AkunController::class, 'editAkunTransaksiProyek'])->name('edit_akun_proyek');
Route::post('edit_akun_kantor', [App\Http\Controllers\AkunController::class, 'editAkunTransaksiKantor'])->name('edit_akun_kantor');
Route::post('edit_proyek', [App\Http\Controllers\AkunController::class, 'editProyek'])->name('edit_proyek');
Route::post('edit_pemasok', [App\Http\Controllers\AkunController::class, 'editPemasok'])->name('edit_pemasok');

// Route Catatan Transaksi Proyek
Route::post('create_transaksi_proyek', [App\Http\Controllers\Catatan\TransaksiProyekController::class, 'insert'])->name('create_transaksi_proyek');
Route::post('update_transaksi_proyek', [App\Http\Controllers\Catatan\TransaksiProyekController::class, 'edit'])->name('update_transaksi_proyek');
Route::post('delete_transaksi_proyek', [App\Http\Controllers\Catatan\TransaksiProyekController::class, 'delete'])->name('delete_transaksi_proyek');

// Route Catatan Transaksi Kantor
Route::post('create_transaksi_kantor', [App\Http\Controllers\Catatan\TransaksiKantorController::class, 'insert'])->name('create_transaksi_kantor');
Route::post('update_transaksi_kantor', [App\Http\Controllers\Catatan\TransaksiKantorController::class, 'edit'])->name('update_transaksi_kantor');
Route::post('delete_transaksi_kantor', [App\Http\Controllers\Catatan\TransaksiKantorController::class, 'delete'])->name('delete_transaksi_kantor');


// Route Anggaran
Route::post('update_anggaran', [App\Http\Controllers\Catatan\AnggaranController::class, 'edit'])->name('update_anggaran');

Route::get('/get_transaksi_proyek/{id}', [App\Http\Controllers\Catatan\TransaksiProyekController::class, 'getById']);
Route::get('/get_transaksi_kantor/{id}', [App\Http\Controllers\Catatan\TransaksiKantorController::class, 'getById']);

//Route Proyek
Route::get('/get_list_proyek/{id}', [App\Http\Controllers\Proyek\ProyekController::class, 'getById'])->name('get_list_proyek_byId');
Route::post('/get_perusahaan', [App\Http\Controllers\Proyek\ProyekController::class, 'getPerusahaan'])->name('get_perusahaan');
Route::post('/list_proyek', [App\Http\Controllers\Proyek\ProyekController::class, 'insert'])->name('list_proyek');
Route::post('update_list_proyek', [App\Http\Controllers\Proyek\ProyekController::class, 'edit'])->name('update_list_proyek');
Route::post('delete_list_proyek', [App\Http\Controllers\Proyek\ProyekController::class, 'delete'])->name('delete_list_proyek');

Route::get('/get_biaya/{id}', [App\Http\Controllers\Proyek\AnggaranController::class, 'getById'])->name('get_biaya_byId');
Route::get('/list_proyek', [App\Http\Controllers\Proyek\ProyekController::class, 'index'])->name('list_proyek');
Route::prefix('list_proyek/{id_proyek}')->name('management_projek.')->group(function () {
    Route::prefix('pendapatan')->name('pendapatan.')->group(function () {
        Route::get('/', [App\Http\Controllers\Catatan\PendapatanController::class, 'list_pendapatan'])->name('index');
        Route::post('/insert', [App\Http\Controllers\Catatan\PendapatanController::class, 'insertPendapatan'])->name('insertPendapatan');
        Route::post('/edit', [App\Http\Controllers\Catatan\PendapatanController::class, 'edit'])->name('edit');
        Route::get('/delete/{id}', [App\Http\Controllers\Catatan\PendapatanController::class, 'delete'])->name('delete');
        Route::post('/insertComment/{id}', [App\Http\Controllers\Catatan\PendapatanController::class, 'insertComment'])->name('insertComment');
    });
    Route::prefix('biaya')->name('biaya.')->group(function () {
        Route::get('/', [App\Http\Controllers\Catatan\AnggaranController::class, 'list_biaya'])->name('index');
        Route::post('/insert', [App\Http\Controllers\Catatan\AnggaranController::class, 'insertBiaya'])->name('insertBiaya');
        Route::post('/insertjenis', [App\Http\Controllers\Catatan\AnggaranController::class, 'insertJenisBiaya'])->name('insertJenisBiaya');
        Route::post('/edit', [App\Http\Controllers\Catatan\AnggaranController::class, 'edit'])->name('edit');

app/Models/Proyek.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Proyek extends Model
{
    use HasFactory;

    protected $fillable = [
        'id_pemilik', 'jenis', 'id_perusahaan', 'kode_proyek', 'status'
    ];

    public function user(){
        return $this->belongsTo('\App\Models\User', 'id_pemilik', 'id');
    }

    public function perusahaan(){
        return $this->belongsTo('\App\Models\Perusahaan', 'id_perusahaan', 'id');
    }

    public function catatan_transaksi_proyek(){
        return $this->hasMany('\App\Models\Catatan\TransaksiProyek', 'id', 'id_proyek');
    }

    public function anggaran(){
        return $this->hasMany('\App\Models\Catatan\Anggaran', 'id', 'id_proyek');
    }
}

app/Http/Controllers/Catatan/PendapatanController.php
<?php

namespace App\Http\Controllers\Catatan;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;

use App\Models\Catatan\Anggaran;
use App\Models\Perusahaan;
use App\Models\AkunTransaksiKantor;
use App\Models\AkunTransaksiProyek;
use App\Models\Manajemen;
use App\Models\AkunNeracaSaldo;
use App\Models\User;
use App\Models\Proyek;
use App\Models\Comments;



class PendapatanController extends Controller
{
    //
    public function index($id_proyek){
        // $perusahaans = Perusahaan::all();
        // $pemiliks = User::all();
        // $proyeks = Proyek::all();
        // $anggarans = Anggaran::all();
        // $akuntransaksikantors = AkunTransaksiKantor::where('jenis', 'Keluar');
        // dd($akuntransaksikantors);
        // return view('proyek.biaya.index', compact('perusahaans', 'pemiliks', 'proyeks', 'akuntransaksikantors', 'anggarans'));
    }

    public function insertPendapatan (Request $request) {
        // dd($request->all());

        // $jumlah = $request->biaya_volume * $request->biaya_hargasatuan;

        $akun = AkunTransaksiProyek::create([
            'nama' => $request->namaPendapatan,
            'jenis' => $request->at_jenis,
            'id_perusahaan' => (User::find(Auth::user()->id))->id_perusahaan,
            'jenis_neraca' => $request->jenis_neraca,
            'jenis' => 'Masuk',
        ]);

        $anggaran = Anggaran::create([
            'id_akun_tr_proyek' => $akun->id,
            'id_perusahaan' => Auth::user()->id_perusahaan,
            'id_proyek' => $request->id_proyek,
            'nominal' => $request->jumlahPendapatan,
        ]);

        // $proyeks = Proyek::where('id_perusahaan', Auth::user()->id_perusahaan)->get();
        // foreach($proyeks as $proyek)
        // {
        //     if($proyek->id == $request->id_proyek)
        //         continue;
        //     Anggaran::create([
        //         'id_akun_tr_proyek' => $akun->id,
        //         'id_perusahaan' => Auth::user()->id_perusahaan,
        //         'id_proyek' => $proyek->id,
        //         'nominal' => 0,
        //     ]);
        // }

        return redirect()->back();
    }



    public function edit(Request $request, $id_proyek)
    {
        $anggaran = Anggaran::find($request->id);
        // dd($anggaran->id_akun_tr_proyek);
        $akuntrproyek = AkunTransaksiProyek::find($anggaran->id_akun_tr_proyek);
        $anggaran->id = $request->id;
        $akuntrproyek->nama = $request->namapendapatan;
        $anggaran->nominal = $request->pendapatanproyek;

        // dd($request->all());

        $anggaran->save();
        $akuntrproyek->save();

        return redirect()->back();
    }

    public function delete($id_proyek, $anggaran)
    {
        // dd($request);
        try {
            $anggarans = Anggaran::find($anggaran);
            $akuntrproyek = AkunTransaksiProyek::find($anggarans->id_akun_tr_proyek)->delete();
            $anggarans->delete();
            // $akuntrproyek->delete()
        } catch (Exception $e) {
            return $e->getMessage();
        }
        return redirect()->back();
    }

    public function list_pendapatan($id_proyek)
    {
        $anggarans = Anggaran::where('id', '=', 'proyeks.id')->get();
        $akun_neraca_saldos = AkunNeracaSaldo::where('id_perusahaan', '=', Auth::user()->id_perusahaan)->get();
        $akunTransaksiProjeks = AkunTransaksiProyek::where([['akun_transaksi_proyeks.jenis', 'Masuk'],['akun_transaksi_proyeks.id_perusahaan', Auth::user()->id_perusahaan]])
            ->join('anggaran_proyek','anggaran_proyek.id_akun_tr_proyek','=','akun_transaksi_proyeks.id')
                // ->join('manajemen', 'manajemen.id', '=', 'akun_transaksi_proyeks.idmanajemen')
                    ->where('anggaran_proyek.id_proyek', '=', $id_proyek)->get();
        // dd($akunTransaksiProjeks);
        // dd($request->all());
        $comment = Comments::where('place', 2)->first();

        return view('proyek.pendapatan.index', compact('comment','akunTransaksiProjeks', 'anggarans', 'id_proyek', 'akun_neraca_saldos'));
    }

    // public function list_pendapatan($id_projek)
    // {
    //     return view('proyek\pendapatan\index');
    // }

    public function insertComment(Request $request, $place)
    {


        $comment = Comments::where('place', $place)->first();

        $comment->comment =  $request->comment;

        $comment->save();

        return redirect()->back();
    }
}

app/Http/Controllers/Proyek/ManajemenProyekController.php
<?php

namespace App\Http\Controllers\Proyek;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use App\Models\Perusahaan;
use App\Models\User;
use App\Models\Proyek;

class ManajemenProyekController extends Controller
{
    //
    public function index(Request $request){
        $perusahaans = Perusahaan::all();
        $pemiliks = User::all();
        $proyeks = Proyek::all();
        return view('proyek.manajemen_proyek', compact('perusahaans', 'pemiliks', 'proyeks'));
    }

    public function insert (Request $request) {
        //dd($request->all());
        $perusahaan = Proyek::create([
            'kode_proyek' => $request->kodeproyek,
            'status' => $request->jenis_status,
            'jenis' => $request->jenisproyek,
            'id_perusahaan' => $request->nama_perusahaan,
            'id_pemilik' => $request->nama_pemilik,
        ]);

        return redirect()->back();
    }

    public function getById($id)
    {
        //dd(json_encode(Proyek::find($id)));
        return json_encode(Proyek::find($id));
    }

    public function edit(Request $request)
    {
        //dd($request);
        $proyek = Proyek::find($request->id);

        $proyek->id_pemilik = $request->nama_pemilik;
        $proyek->jenis = $request->jenisproyek;
        $proyek->status = $request->jenis_status;
        $proyek->id_perusahaan = $request->nama_perusahaan;
        $proyek->kode_proyek = $request->kodeproyek;

        $proyek->save();

        return redirect()->route('list_proyek');
    }

    public function delete(Request $request)
    {
        // dd($request);
        try {
            Proyek::find($request->id)->delete();
        } catch (Exception $e) {
            return $e->getMessage();
        }
        return $request->id;
    }

    public function getPerusahaan(Request $request)
    {
        $pemiliks = User::find($request->id)->perusahaan;
        return $pemiliks;
    }
}

resources/views/proyek/pendapatan/index.blade.php
@extends('adminlte::page')

@section('title', 'Keuangan Kapal | Pendapatan')

@section('content_header')
<h5 class="pl-3"><b>Pendapatan</b></h5>
@endsection

@section('content')
<!-- <script src = "https://ajax.googleapis.com/ajax/libs/jquery/2.1.3/jquery.min.js"></script> -->
<meta name="csrf-token" content="{{ csrf_token() }}" />
@if(!empty(Auth::user()->id_perusahaan))
<div class="card">
    <div class="card-header">
        <div class="row">
            <div class="col-sm">
                <div class="row justify-content-start pl-2 pt-2">
                    <a href="{{ route('list_proyek') }}"><button type="button" class="btn btn-sm btn-secondary mr-2"><i class="fas fa-arrow-left"></i> Kembali</button></a>
                    @if(Auth::user()->role == 1 || Auth::user()->role == 2)
                    <a href="#"><button type="button" class="btn btn-sm btn-primary mr-2" data-toggle="modal" data-target="#exampleModal"><i class="fas fa-plus"></i> Pendapatan</button></a>
                    @endif
                </div>
            </div>
        </div>
    </div>
    {{-- <div class="card-header">
        <div class="row">
            <div class="col-sm">
                @if(Auth::user()->role == 1 || Auth::user()->role == 2)
                <div class="row justify-content-start pl-2 pt-2">
                    <a href="#"><button type="button" class="btn btn-sm btn-primary mr-2 " data-toggle="modal" data-target="#exampleModal"><i class="fas fa-plus"></i> Tambah</button></a>
                </div>
                @endif
            </div>
        </div>
    </div> --}}
    <!-- /.card-header -->

    <div class="card-body ">
        <div class="dataTables_wrapper">
            <table id="myTable" class="display table table-stripped table-hover table-condensed table-sm dataTable">
                <thead>
                    <tr style="text-align: center">
                        <th scope="col">Jenis Proyek</th>
                        <th scope="col">Nama Pendapatan</th>
                        <th scope="col">Pendapatan Proyek</th>
                        @if(Auth::user()->role == 1 || Auth::user()->role == 2)
                        <th scope="col">Aksi</th>
                        @endif
                    </tr>
                </thead>
                <tbody>
                    @foreach ($akunTransaksiProjeks as $projeks)
                    <tr style="text-align: center">
                        <td>
                            Pendapatan
                        </td>
                        <td>
                            {{ $projeks->nama }}
                        </td>
                        <td>
                            {{
                                number_format($projeks->nominal, 2, '.', ',')
                            }}
                            {{-- {{ $projeks->nominal }} --}}
                        </td>
                        @if(Auth::user()->role == 1 || Auth::user()->role == 2)
                        <td>
                            <button id="bEdit" type="button" class="btn btn-sm btn-link p-0 mx-1" data-toggle="modal" data-target="#editModal{{$projeks->id}}"><i class="fas fa-pencil-alt" > </i></button>
                            <a href="{{ route('management_projek.pendapatan.delete', ['id_proyek' => $id_proyek, 'id' => $projeks->id]) }}" class="btn btn-sm btn-link p-0 mx-1" onclick="return confirm('Apakah anda ingin menghapus data ini?')"><i class="fas fa-trash-alt" > </i></a>
                        </td>
                        @endif
                    </tr>
                    @endforeach
                </tbody>
            </table>
        </div>
    </div>

    <div class="card-body ">
        <div class="mx-auto float-right"><strong>Total Pendapatan Proyek</strong>
            <p class="mx-3">&nbsp {{number_format($akunTransaksiProjeks->sum('nominal'), 2, '.', ',')}}</p>
        </div>
    </div>
    <div class="card-body">
                <div class="row">
                    <div class="col-12 h6">
                        <b>
                            Komentar
                        </b>
                    </div>
                <div class="col-11">
                    {{$comment->comment}}
                </div>
                <div class="col-1">
                    @if(Auth::user()->role == 3)
                        <button id="bEdit" type="button" class="btn btn-sm btn-link p-0 mx-1" data-toggle="modal" data-target="#editCommentModal"><i class="fas fa-pencil-alt" > </i></button>
                    @endif
                </div>
            </div>
        </div>
    </div>

    <div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel">Jenis Biaya</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
            <div class="modal-body">
            <form id="add-transaksi" method="post" action="{{ route('management_projek.pendapatan.insertPendapatan',['id_proyek' => $id_proyek]) }}">
                @csrf
                <div class="form-group">
                    <label for="namaPendapatan">Nama Pendapatan</label>
                    <input autocomplete="off" type="text" id="namaPendapatan" name="namaPendapatan" class="form-control">
                </div>
                <div id="jenis_neraca" class="form-group">
                    <label>Jenis Neraca</label>
                    <select class="form-control" name="jenis_neraca">
                    <option value="Aset Lancar">Aset Lancar</option>
                    <option value="Aset Tetap">Aset Tetap</option>
                    <option value="Kewajiban Lancar">Kewajiban Lancar</option>
                    <option value="Kewajiban Panjang">Kewajiban Jangka Panjang</option>
                    <option value="Ekuitas">Ekuitas</option>
                    </select>
                </div>
                <div class="form-group">
                    <label for="jumlahPendapatan">Jumlah Pendapatan</label>
                    <input autocomplete="off" type=number step=0.001 id="jumlahPendapatan" name="jumlahPendapatan" class="form-control">
                </div>
            </form>
        </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                    <button type="submit" class="btn btn-primary" form="add-transaksi">Simpan</button>
                </div>
            </div>
        </div>
    </div>
    <!-- /.card-body -->
    @foreach ($akunTransaksiProjeks as $projeks)
    <div class="modal fade" id="editModal{{$projeks->id}}" tabindex="-1" role="dialog" aria-labelledby="editModalLabel" aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="editModalLabel">Edit Pendapatan</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    <form id="edit-transaksi{{$projeks->id}}" method="post" action="{{ route('management_projek.pendapatan.edit',['id_proyek' => $id_proyek]) }}">
                        @csrf
                        <input id="edit-id" name="id" type="hidden" class="form-control" value="{{$projeks->id}}">
                        <div class="form-group">
                            <label for="edit-namapendapatan">Nama Pendapatan</label>
                            <input autocomplete="off" type="text" id="edit-namapendapatan" name="namapendapatan" class="form-control" value="{{$projeks->nama}}">
                        </div>
                        <div class="form-group">
                            <label for="edit-pendapatanproyek">Pendapatan Proyek</label>
                            <input autocomplete="off" type="number" id="edit-pendapatanproyek" name="pendapatanproyek" class="form-control" value="{{$projeks->nominal}}">
                        </div>
                    </form>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                    <button type="submit" class="btn btn-primary" form="edit-transaksi{{$projeks->id}}">Simpan</button>
                </div>
            </div>
        </div>
    </div>

    {{-- Edit detail biaya --}}
    @endforeach
    <div class="modal fade" id="editCommentModal" tabindex="-1" role="dialog" aria-labelledby="editCommentModalLabel" aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="editCommentModalLabel">Edit Komentar</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    <form id="edit-comment-transaksi" method="post" action="{{ route('insertComment',  ['place' => 2]) }}">
                        @csrf
                        <div class="form-group">
                            <label for="edit-komentar">Komentar</label>
                            <input autocomplete="off" type="text" id="edit-komentar" name="comment" class="form-control" value="{{$comment->comment}}" >
                        </div>
                    </form>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                    <button type="submit" class="btn btn-primary" form="edit-comment-transaksi">Simpan</button>
                </div>
            </div>
        </div>
    </div>
    <div class="card-footer">
    </div>
    <!-- /.card-footer -->
</div>
@endif
@endsection

@section('css')
<link rel="stylesheet" href="/css/admin_custom.css">
<style>
.content {
    font-size: 12px;
}
</style>
<meta name="csrf-token" content="{{ Session::token() }}">
@endsection

@section('js')
<script src="https://unpkg.com/autonumeric"></script>
<script type="text/javascript">
    $(document).ready(function() {
            $('#myTable').DataTable( {

                order: [[0, 'asc'], [1, 'asc'], [2, 'asc']],
                rowGroup: {
                    dataSrc: [ 0 ] //parents
                },
                columnDefs: [ {
                    targets: [ 0 ], //hiden header coloum (dibalik" sama aja)
                    visible: false
                } ]
            } );
        } );
</script>

<script src="{{ asset('js/bootstable-list-proyek.js') }}"></script>

@endsection