routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('front.welcome');
});

Route::get('/print', function () {
    return view('print');
});
// Route::get('/login', function() {
//     return view('front.login');
// })->name('login');

Auth::routes();
Route::get('register/{token?}', [App\Http\Controllers\Auth\RegisterController::class, 'view'])->name('reg');
Route::get('register', [App\Http\Controllers\Auth\RegisterController::class, 'view']);

// Route::post('add_akun_transaksi_kantor', 'AkunController@insertTransaksiKantor')->name('add_akun_transaksi_kantor');
Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');
Route::get('/profil_perusahaan', [App\Http\Controllers\DashboardController::class, 'pageProfilPerusahaan'])->name('profil_perusahaan');
Route::get('/data', [App\Http\Controllers\DashboardController::class, 'PageData'])->name('data');
Route::get('/anggaran', [App\Http\Controllers\CatatanController::class, 'pageAnggaran'])->name('anggaran');
Route::get('/neraca/{date_range?}', [App\Http\Controllers\CatatanController::class, 'pageNeraca'])->name('neraca');
Route::get('/transaksi_proyek/{date_range?}', [App\Http\Controllers\CatatanController::class, 'pageTransaksiProyek'])->name('transaksi_proyek');
Route::get('/transaksi_proyek_with_type/{type?}', [App\Http\Controllers\CatatanController::class, 'pageTransaksiProyekWithType'])->name('transaksi_proyek_withfilter');
Route::get('/transaksi_kantor/{date_range?}', [App\Http\Controllers\CatatanController::class, 'pageTransaksiKantor'])->name('transaksi_kantor');
Route::get('/transaksi_kantor_with_type/{type?}', [App\Http\Controllers\CatatanController::class, 'pageTransaksiKantorWithType'])->name('transaksi_kantor_with_type');
Route::get('/hutang_piutang', [App\Http\Controllers\CatatanController::class, 'pageHutangPiutang'])->name('hutang_piutang');
Route::get('/gudang/{date_range?}', [App\Http\Controllers\GudangController::class, 'pageGudang'])->name('gudang');
Route::get('/profile', [App\Http\Controllers\ProfileController::class, 'index'])->name('profile');

Route::get('/manajemen_proyek', [App\Http\Controllers\Proyek\ManajemenProyekController::class, 'index'])->name('manajemen_proyek');
Route::post('/users/update', [App\Http\Controllers\ProfileController::class,'update'])->name('users.update');

Route::get('/laba_rugi/{id_proyek?}/{date_range?}', [App\Http\Controllers\LaporanController::class, 'pageLabaRugi'])->name('laba_rugi');
Route::get('/laba_rugi_proyek/{id_proyek?}/{date_range?}', [App\Http\Controllers\LaporanController::class, 'pageLabaRugiProyek'])->name('laba_rugi_proyek');
Route::get('/laba_rugi_kantor/{date_range?}', [App\Http\Controllers\LaporanController::class, 'pageLabaRugiKantor'])->name('laba_rugi_kantor');

//Route edit perusahaan
Route::prefix('perusahaan')->name('perusahaan.')->group(function () {
    Route::post('/edit', [App\Http\Controllers\DashboardController::class, 'edit'])->name('edit');
    // Route::get('/delete/{id}', [App\Http\Controllers\GudangController::class, 'delete'])->name('delete');
});

// Route perusahaan
Route::post('create_perusahaan', [App\Http\Controllers\dashboard\PerusahaanController::class, 'insert'])->name('create_perusahaan');
Route::post('invite_anggota', [App\Http\Controllers\dashboard\PerusahaanController::class, 'invite'])->name('invite_anggota');
Route::post('acc_invite', [App\Http\Controllers\dashboard\PerusahaanController::class, 'acc_invite'])->name('acc_invite');
Route::post('rej_invite', [App\Http\Controllers\dashboard\PerusahaanController::class, 'rej_invite'])->name('rej_invite');
Route::post('edit_role', [App\Http\Controllers\dashboard\PerusahaanController::class, 'edit_role'])->name('edit_role');
Route::post('delete_member', [App\Http\Controllers\dashboard\PerusahaanController::class, 'delete_member'])->name('delete_member');

//Route Gudang
Route::post('create_gudang', [App\Http\Controllers\GudangController::class, 'create'])->name('create_gudang');
Route::prefix('gudang')->name('gudang.')->group(function () {
    Route::post('/edit', [App\Http\Controllers\GudangController::class, 'edit'])->name('edit');
    Route::get('/delete/{id}', [App\Http\Controllers\GudangController::class, 'delete'])->name('delete');
});
Route::post('form_neraca', [App\Http\Controllers\AkunController::class, 'addAkunNeraca'])->name('form_neraca');
Route::post('form_pemasok', [App\Http\Controllers\AkunController::class, 'addPemasok'])->name('form_pemasok');
Route::post('form_proyek', [App\Http\Controllers\AkunController::class, 'addProyek'])->name('form_proyek');
Route::post('form_transaksi_proyek', [App\Http\Controllers\AkunController::class, 'addAkunTransaksiProyek'])->name('form_transaksi_proyek');
Route::post('form_transaksi_kantor', [App\Http\Controllers\AkunController::class, 'addAkunTransaksiKantor'])->name('form_transaksi_kantor');

Route::get('/delete_neraca/{nama}', [App\Http\Controllers\AkunController::class, 'delAkunNeraca']);
Route::get('/delete_akun_kantor/{nama}', [App\Http\Controllers\AkunController::class, 'delAkunTransaksiKantor']);
Route::get('/delete_akun_proyek/{nama}', [App\Http\Controllers\AkunController::class, 'delAkunTransaksiProyek']);
Route::get('/delete_pemasok/{nama}', [App\Http\Controllers\AkunController::class, 'delPemasok']);
Route::get('/delete_proyek/{nama}', [App\Http\Controllers\AkunController::class, 'delProyek']);

Route::post('edit_neraca', [App\Http\Controllers\AkunController::class, 'editAkunNeraca'])->name('edit_neraca');
Route::post('edit_akun_proyek', [App\Http\Controllers\AkunController::class, 'editAkunTransaksiProyek'])->name('edit_akun_proyek');
Route::post('edit_akun_kantor', [App\Http\Controllers\AkunController::class, 'editAkunTransaksiKantor'])->name('edit_akun_kantor');
Route::post('edit_proyek', [App\Http\Controllers\AkunController::class, 'editProyek'])->name('edit_proyek');
Route::post('edit_pemasok', [App\Http\Controllers\AkunController::class, 'editPemasok'])->name('edit_pemasok');

// Route Catatan Transaksi Proyek
Route::post('create_transaksi_proyek', [App\Http\Controllers\Catatan\TransaksiProyekController::class, 'insert'])->name('create_transaksi_proyek');
Route::post('update_transaksi_proyek', [App\Http\Controllers\Catatan\TransaksiProyekController::class, 'edit'])->name('update_transaksi_proyek');
Route::post('delete_transaksi_proyek', [App\Http\Controllers\Catatan\TransaksiProyekController::class, 'delete'])->name('delete_transaksi_proyek');

// Route Catatan Transaksi Kantor
Route::post('create_transaksi_kantor', [App\Http\Controllers\Catatan\TransaksiKantorController::class, 'insert'])->name('create_transaksi_kantor');
Route::post('update_transaksi_kantor', [App\Http\Controllers\Catatan\TransaksiKantorController::class, 'edit'])->name('update_transaksi_kantor');
Route::post('delete_transaksi_kantor', [App\Http\Controllers\Catatan\TransaksiKantorController::class, 'delete'])->name('delete_transaksi_kantor');


// Route Anggaran
Route::post('update_anggaran', [App\Http\Controllers\Catatan\AnggaranController::class, 'edit'])->name('update_anggaran');

Route::get('/get_transaksi_proyek/{id}', [App\Http\Controllers\Catatan\TransaksiProyekController::class, 'getById']);
Route::get('/get_transaksi_kantor/{id}', [App\Http\Controllers\Catatan\TransaksiKantorController::class, 'getById']);

//Route Proyek
Route::get('/get_list_proyek/{id}', [App\Http\Controllers\Proyek\ProyekController::class, 'getById'])->name('get_list_proyek_byId');
Route::post('/get_perusahaan', [App\Http\Controllers\Proyek\ProyekController::class, 'getPerusahaan'])->name('get_perusahaan');
Route::post('/list_proyek', [App\Http\Controllers\Proyek\ProyekController::class, 'insert'])->name('list_proyek');
Route::post('update_list_proyek', [App\Http\Controllers\Proyek\ProyekController::class, 'edit'])->name('update_list_proyek');
Route::post('delete_list_proyek', [App\Http\Controllers\Proyek\ProyekController::class, 'delete'])->name('delete_list_proyek');

Route::get('/get_biaya/{id}', [App\Http\Controllers\Proyek\AnggaranController::class, 'getById'])->name('get_biaya_byId');
Route::get('/list_proyek', [App\Http\Controllers\Proyek\ProyekController::class, 'index'])->name('list_proyek');
Route::prefix('list_proyek/{id_proyek}')->name('management_projek.')->group(function () {
    Route::prefix('pendapatan')->name('pendapatan.')->group(function () {
        Route::get('/', [App\Http\Controllers\Catatan\PendapatanController::class, 'list_pendapatan'])->name('index');
        Route::post('/insert', [App\Http\Controllers\Catatan\PendapatanController::class, 'insertPendapatan'])->name('insertPendapatan');
        Route::post('/edit', [App\Http\Controllers\Catatan\PendapatanController::class, 'edit'])->name('edit');
        Route::get('/delete/{id}', [App\Http\Controllers\Catatan\PendapatanController::class, 'delete'])->name('delete');
        Route::post('/insertComment/{id}', [App\Http\Controllers\Catatan\PendapatanController::class, 'insertComment'])->name('insertComment');
    });
    Route::prefix('biaya')->name('biaya.')->group(function () {
        Route::get('/', [App\Http\Controllers\Catatan\AnggaranController::class, 'list_biaya'])->name('index');
        Route::post('/insert', [App\Http\Controllers\Catatan\AnggaranController::class, 'insertBiaya'])->name('insertBiaya');
        Route::post('/insertjenis', [App\Http\Controllers\Catatan\AnggaranController::class, 'insertJenisBiaya'])->name('insertJenisBiaya');
        Route::post('/edit', [App\Http\Controllers\Catatan\AnggaranController::class, 'edit'])->name('edit');

app/Models/Proyek.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Proyek extends Model
{
    use HasFactory;

    protected $fillable = [
        'id_pemilik', 'jenis', 'id_perusahaan', 'kode_proyek', 'status'
    ];

    public function user(){
        return $this->belongsTo('\App\Models\User', 'id_pemilik', 'id');
    }

    public function perusahaan(){
        return $this->belongsTo('\App\Models\Perusahaan', 'id_perusahaan', 'id');
    }

    public function catatan_transaksi_proyek(){
        return $this->hasMany('\App\Models\Catatan\TransaksiProyek', 'id', 'id_proyek');
    }

    public function anggaran(){
        return $this->hasMany('\App\Models\Catatan\Anggaran', 'id', 'id_proyek');
    }
}

app/Http/Controllers/Proyek/ManajemenProyekController.php
<?php

namespace App\Http\Controllers\Proyek;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use App\Models\Perusahaan;
use App\Models\User;
use App\Models\Proyek;

class ManajemenProyekController extends Controller
{
    //
    public function index(Request $request){
        $perusahaans = Perusahaan::all();
        $pemiliks = User::all();
        $proyeks = Proyek::all();
        return view('proyek.manajemen_proyek', compact('perusahaans', 'pemiliks', 'proyeks'));
    }

    public function insert (Request $request) {
        //dd($request->all());
        $perusahaan = Proyek::create([
            'kode_proyek' => $request->kodeproyek,
            'status' => $request->jenis_status,
            'jenis' => $request->jenisproyek,
            'id_perusahaan' => $request->nama_perusahaan,
            'id_pemilik' => $request->nama_pemilik,
        ]);

        return redirect()->back();
    }

    public function getById($id)
    {
        //dd(json_encode(Proyek::find($id)));
        return json_encode(Proyek::find($id));
    }

    public function edit(Request $request)
    {
        //dd($request);
        $proyek = Proyek::find($request->id);

        $proyek->id_pemilik = $request->nama_pemilik;
        $proyek->jenis = $request->jenisproyek;
        $proyek->status = $request->jenis_status;
        $proyek->id_perusahaan = $request->nama_perusahaan;
        $proyek->kode_proyek = $request->kodeproyek;

        $proyek->save();

        return redirect()->route('list_proyek');
    }

    public function delete(Request $request)
    {
        // dd($request);
        try {
            Proyek::find($request->id)->delete();
        } catch (Exception $e) {
            return $e->getMessage();
        }
        return $request->id;
    }

    public function getPerusahaan(Request $request)
    {
        $pemiliks = User::find($request->id)->perusahaan;
        return $pemiliks;
    }
}

app/Http/Controllers/Proyek/ProyekController.php
<?php

namespace App\Http\Controllers\Proyek;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use App\Models\Perusahaan;
use App\Models\User;
use App\Models\Proyek;

class ProyekController extends Controller
{
    //
    public function index(Request $request){
        $perusahaans = Perusahaan::all();
        $pemiliks = User::all();
        $proyeks = Proyek::all();
        return view('proyek.list_proyek', compact('perusahaans', 'pemiliks', 'proyeks'));
    }

    public function insert (Request $request) {
        //dd($request->all());
        $perusahaan = Proyek::create([
            'kode_proyek' => $request->kodeproyek,
            'status' => $request->jenis_status,
            'jenis' => $request->jenisproyek,
            'id_perusahaan' => $request->nama_perusahaan,
            'id_pemilik' => $request->nama_pemilik,
        ]);

        return redirect()->back();
    }

    public function getById($id)
    {
        //dd(json_encode(Proyek::find($id)));
        return json_encode(Proyek::find($id));
    }

    public function edit(Request $request)
    {
        //dd($request->all());
        $proyek = Proyek::find($request->id);

        $proyek->id_pemilik = $request->nama_pemilik;
        $proyek->jenis = $request->jenisproyek;
        $proyek->status = $request->jenis_status;
        $proyek->id_perusahaan = $request->nama_perusahaan;
        $proyek->kode_proyek = $request->kodeproyek;

        $proyek->save();

        return redirect()->route('list_proyek');
    }

    public function delete(Request $request)
    {
        // dd($request);
        try {
            Proyek::find($request->id)->delete();
        } catch (Exception $e) {
            return $e->getMessage();
        }
        return $request->id;
    }

    public function getPerusahaan(Request $request)
    {
        $pemiliks = User::find($request->id)->perusahaan;
        return $pemiliks;
    }
}

resources/views/proyek/list_proyek.blade.php
@extends('adminlte::page')

@section('title', 'Keuangan Kapal | List Proyek')

@section('content_header')
<h5 class="pl-3"><b>LIST PROYEK</b></h5>
@endsection

@section('content')
<!-- <script src = "https://ajax.googleapis.com/ajax/libs/jquery/2.1.3/jquery.min.js"></script> -->
<meta name="csrf-token" content="{{ csrf_token() }}" />
@if(!empty(Auth::user()->id_perusahaan))
<div class="card">
    <div class="card-header">
        <div class="row">
            <div class="col-sm">
                @if(Auth::user()->role == 1 || Auth::user()->role == 2)
                <div class="row justify-content-start pl-2 pt-2">
                    <a href="#"><button type="button" class="btn btn-sm btn-primary mr-2 " data-toggle="modal" data-target="#exampleModal"><i class="fas fa-plus"></i> Tambah</button></a>
                </div>
                @endif
            </div>
        </div>
    </div>
    <!-- /.card-header -->

    <div class="card-body ">
        <div class="dataTables_wrapper">
            <table id="table-transaksi-kantor" class="display table table-stripped table-hover table-condensed table-sm dataTable">
                <thead>
                    <tr>
                        <th scope="col">Nama Perusahaan</th>
                        <th scope="col">Nama Pemilik</th>
                        <th scope="col">Kode Proyek</th>
                        <th scope="col">Status Proyek</th>
                        <th scope="col">Jenis Proyek</th>
                        <th scope="col" class="text-center">Aksi</th>
                    </tr>
                </thead>
                <tbody>
                        @foreach ($proyeks as $proyek)
                            <tr id="{{ $proyek->id }}">
                                <td>
                                    {{$proyek->perusahaan->nama_perusahaan}}
                                </td>
                                <td>
                                    {{$proyek->user->name}}
                                </td>
                                <td>
                                    {{$proyek->kode_proyek}}
                                </td>
                                <td>
                                    {{$proyek->status}}
                                </td>
                                <td>
                                    {{$proyek->jenis}}
                                </td>
                                <td class="text-center">
                                @if(Auth::user()->role == 1 || Auth::user()->role == 2)
                                    <button id="bEdit" type="button" onclick="rowEdit(this);" class="btn btn-sm btn-link p-0 mx-1" data-toggle="modal"><i class="fas fa-pencil-alt" > </i></button>
                                    <button id="bElim" type="button" onclick="rowElim(this);" class="btn btn-sm btn-link p-0 mx-1" ><i class="fas fa-trash-alt" > </i></button>
                                @endif
                                    <a href="{{ route('management_projek.pendapatan.index', ['id_proyek' => $proyek->id]) }}" class="btn btn-sm btn-link p-0 mx-1" ><i class="fas fa-wallet" > </i></a>
                                    <a href="{{ route('management_projek.biaya.index', ['id_proyek' => $proyek->id]) }}" class="btn btn-sm btn-link p-0 mx-1" ><i class="fas fa-shopping-cart" > </i></a>
                                </td>
                            </tr>
                        @endforeach
                </tbody>
            </table>
        </div>
    </div>
    <!-- /.card-body -->

    <div class="card-footer">
    </div>
    <!-- /.card-footer -->
</div>

@if(Auth::user()->role == 1 || Auth::user()->role == 2)
<!-- Modal -->
<div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Tambah Data</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
      <form id="add-transaksi" method="post" action="{{ route('list_proyek') }}">
        @csrf
            <div class="form-group">
            <label for="kodeproyek">Kode Proyek</label>
                <input autocomplete="off" type="text" id="kodeproyek" name="kodeproyek" class="form-control">
            </div>
            <div class="form-group">
                <label for="jenis-akun">Status Proyek</label>
                <select class="form-control" id="jenis-status" name="jenis_status" required>
                <option disabled selected value> -- pilih status proyek -- </option>
                <option value="Aktif">Aktif</option>
                <option value="Selesai">Selesai</option>
                </select>
            </div>
            <div class="form-group">
                <label for="jenis-akun">Nama Perusahaan</label>
                <select class="form-control" id="nama-perusahaan" name="nama_perusahaan" required>

                {{-- @foreach ($perusahaans as $perusahaan)
                    <option value="{{$perusahaan->id}}">{{$perusahaan->nama_perusahaan}}</option>
                @endforeach --}}
                </select>
            </div>
            <div class="form-group">
                <label for="jenis-akun">Nama Pemilik</label>
                <select class="form-control" id="nama-pemilik" name="nama_pemilik" required>
                <option disabled selected value> -- pilih pemilik -- </option>
                @foreach ($pemiliks as $pemilik)
                    <option value="{{$pemilik->id}}">{{$pemilik->name}}</option>
                @endforeach
                </select>
            </div>
            <div class="form-group">
                <label for="jenisproyek">Jenis Proyek</label>
                <input autocomplete="off" type="text" id="jenisproyek" name="jenisproyek"  class="form-control">
            </div>
            <!-- <div class="form-group">
                <label for="kas-bank">Kas/Bank</label>
                <select class="form-control" id="kas-bank" name="akun_neraca" required>
                <option disabled selected value> -- pilih akun -- </option>
                </select>
            </div>
            <div class="form-group">
                <div class="form-group">
                    <label for="jumlah-transaksi">Jumlah (Rp)</label>
                    <input type="text" id="jumlah-transaksi" class="form-control" name="jumlah_transaksi" required>
                </div>
            </div> -->
        </form>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
        <button type="submit" class="btn btn-primary" form="add-transaksi">Simpan</button>
      </div>
    </div>
  </div>
</div>

<!-- Modal -->
<div class="modal fade" id="editModal" tabindex="-1" role="dialog" aria-labelledby="editModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="editModalLabel">Edit Data</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <form id="edit-transaksi" method="post" action="{{ route('update_list_proyek') }}">
                    @csrf
                    <input id="edit-id" name="id" type="hidden" class="form-control">
                    <div class="form-group">
                        <label for="kodeproyek">Kode Proyek</label>
                        <input autocomplete="off" type="text" id="edit-kodeproyek" name="kodeproyek" class="form-control">
                    </div>
                    <div class="form-group">
                        <label for="status-proyek">Status Proyek</label>
                        <select class="form-control" id="edit-jenis-status" name="jenis_status" required>
                            <option disabled selected value> -- pilih status proyek -- </option>
                            <option value="Aktif">Aktif</option>
                            <option value="Selesai">Selesai</option>
                        </select>
                    </div>
                    <div class="form-group">
                        <label for="jenis-akun">Nama Perusahaan</label>
                        <select class="form-control" id="edit-nama-perusahaan" name="nama_perusahaan" required>
                            <option disabled selected value> -- pilih perusahaan -- </option>
                            @foreach ($perusahaans as $perusahaan)
                            <option value="{{$perusahaan->id}}">{{$perusahaan->nama_perusahaan}}</option>
                            @endforeach
                        </select>
                    </div>
                    <div class="form-group">
                        <label for="jenis-akun">Nama Pemilik</label>
                        <select class="form-control" id="edit-nama-pemilik" name="nama_pemilik" required>
                            <option disabled selected value> -- pilih pemilik -- </option>
                            @foreach ($pemiliks as $pemilik)
                            <option value="{{$pemilik->id}}">{{$pemilik->name}}</option>
                            @endforeach
                        </select>
                    </div>
                    <div class="form-group">
                        <label for="jenisproyek">Jenis Proyek</label>
                        <input autocomplete="off" type="text" id="edit-jenisproyek" name="jenisproyek"  class="form-control" value="{{$proyek->jenis}}">
                    </div>
                </form>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                <button type="submit" class="btn btn-primary" form="edit-transaksi">Simpan</button>
            </div>
        </div>
    </div>
</div>
@endif
@endif
@endsection

@section('css')
<link rel="stylesheet" href="/css/admin_custom.css">
<style>
.content {
    font-size: 12px;
}
</style>
<meta name="csrf-token" content="{{ Session::token() }}">
@endsection

@section('js')
<script src="https://unpkg.com/autonumeric"></script>
<script type="text/javascript">
    const pemilik=document.getElementById('nama-pemilik');
    //console.log(pemilik);
    pemilik.addEventListener('change', (e)=>{
        $.ajax({
            url: '{{route("get_perusahaan")}}',
            data: {
                '_token':"{{csrf_token()}}",
                'id':e.srcElement.value
            },
            error: function(xhr,status,error) {

            },
            success: function(data) {
                let newOption = '<option disabled selected value> -- pilih perusahaan -- </option>';
                newOption+=`<option value=${data.id}>${data.nama_perusahaan}</option>`
                const perusahaan = document.querySelector('#nama-perusahaan');
                perusahaan.innerHTML = newOption;
            },
            type: 'POST',
            async: true
        });
    })
    $(document).ready(function() {
        var role = <?php echo Auth::user()->role; ?>;

        if(role == 1)
        {
            $('table').SetEditable();
        }

        var columnDefs = [];
        if(role == 1){
            columnDefs = [
                { "width": "20px", "targets": [4,5,6,8,9,13] },
                { "targets": [2, 3, 4, 5, 6, 7, 8], "orderable": false }
            ]
        }
        else{
            columnDefs = [
                { "width": "20px", "targets": [3,4,5,7,8,12] },
                { "targets": [1, 2, 3, 4, 5, 6, 7], "orderable": false }
            ]
        }

        $('#table-transaksi-kantor').DataTable({
            'columnDefs': columnDefs,
            'paging': false,
            'lengthChange': false,
            'searching': false,
            'ordering': true,
            'info': false,
            'autoWidth': false,
            'scrollY': 700,
            'scrollCollapse': true,
        });
    });
</script>
<script>
    $(function() {
        $('input[name="daterange"]').daterangepicker({
            opens: 'center',
            autoUpdateInput: false,
            locale: {
                format: 'DD/MM/YYYY',
            },
        }, function(start, end, label) {
            start = start.format('DD-MM-YYYY');
            end = end.format('DD-MM-YYYY');
            var all = start + ' - ' + end;
            var url = '/transaksi_kantor/' + encodeURIComponent(all);
            console.log(all);
            console.log(url);
            window.location.href = url;
            // console.log("A new date selection was made: " + start + ' to ' + end);
        });
        $('input[name="tgl_transaksi"]').daterangepicker({
            singleDatePicker: true,
            showDropdowns: true,
            minYear: 1901,
            maxYear: parseInt(moment().format('YYYY'), 10),
            locale: {
                format: 'DD/MM/YYYY',
            }
        });
    });
</script>

<script src="{{ asset('js/bootstable-list-proyek.js') }}"></script>

@endsection